{{- $fullName := include "pgwatch2.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgwatch2.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pgwatch2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
      {{- toYaml .Values.metadata.annotations | nindent 8 }}
      labels:
        app.kubernetes.io/name: {{ include "pgwatch2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{ if .Values.env.PW2_CONFIG }}
        - name: pgwatch2-sc-database
          image: "{{ .Values.confdbsidecar.image.repository }}:{{ .Values.confdbsidecar.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: LABEL
              value: pgwatch2_database
            - name: FOLDER
              value: {{ .Values.env.PW2_CONFIG }}
            - name: RESOURCE
              value: both
          volumeMounts:
            - name: sc-database-volume
              mountPath: {{ .Values.env.PW2_CONFIG }}
          {{ end }}
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $pkey, $pval := .Values.env }}
            - name: {{ $pkey }}
              value: {{ quote $pval }}
            {{- end }}
          ports:
            - name: pgwatch-adm
              containerPort: 8080
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: pgwatch-adm
          readinessProbe:
            httpGet:
              path: /
              port: pgwatch-adm
        {{ if .Values.env.PW2_CONFIG }}
          volumeMounts:
              - name: sc-database-volume
                mountPath: {{ .Values.env.PW2_CONFIG }}
        {{ end }}
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}

      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  {{ if .Values.env.PW2_CONFIG }}
      volumes:
        - name: sc-database-volume
          emptyDir: {}
  {{ end }}


