{{- if .Values.ingress.adm.enabled -}}
{{- $fullName := include "pgwatch2.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "pgwatch2.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if or (.Values.ingress.adm.tls) (.Values.ingress.grafana.tls) }}
  tls:
    - hosts:
      {{- if .Values.ingress.adm.tls }}
      -  {{ .Values.ingress.adm.tls.host }}
      secretName: {{ .Values.ingress.adm.tls.secretName }}
      {{ end}}
      {{- if .Values.ingress.grafana.tls }}
      -  {{ .Values.ingress.grafana.tls.host }}
      secretName: {{ .Values.ingress.grafana.tls.secretName }}
      {{ end}}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.adm.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "pgwatch2.fullname" . }}
              servicePort: {{ .Values.service.admport }}
    {{- if .Values.ingress.grafana.enable }}
    - host: {{ .Values.ingress.grafana.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "pgwatch2.fullname" . }}
              servicePort: {{ .Values.service.grafanaport }}
          {{- end }}
  {{- end }}
