{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pgwatch2.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "pgwatch2.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      -  {{ .Values.ingress.tls.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.adm.path }}
            backend:
              serviceName: pgwatch-adm
              servicePort: {{ .Values.service.admport }}
          {{- if .Values.ingress.grafana.enable }}
          - path: {{ .Values.ingress.grafana.path }}
            backend:
              serviceName: grafana
              servicePort: {{ .Values.service.grafanaport }}
          {{- end }}
  {{- end }}
