apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgwatch2.fullname" . }}
  labels:
{{ include "pgwatch2.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.admport }}
      targetPort: pgwatch-adm
      protocol: TCP
      name: pgwatch-adm
    - port: {{ .Values.service.grafanaport }}
      targetPort: pgwatch-adm
      protocol: TCP
      name: grafana
  selector:
    app.kubernetes.io/name: {{ include "pgwatch2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
