# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: clean repo
      run: find . -maxdepth 1 -type f -exec rm "{}" \;
    # Runs a single command using the runners shell
    - name: Helm lint 
      run: find . -type  d  -maxdepth 1 -not -path "./.*" -not -path "." -exec helm lint "{}" \;

    # Runs a set of commands using the runners shell
    - name: helm package
      run: find . -type  d  -maxdepth 1 -not -path "./.*" -not -path "." -exec helm package "{}" \;
    - uses: secrethub/actions/env-export@v0.1.0
      env:
         TOKEN=${{ secrets.PERSONAL_TOKEN }}
    - name: helm push
      env: TOKEN=${{ secrets.PERSONAL_TOKEN }}
      run: for CHART in $(find . -type f -path "*.tgz"  -exec  basename {} \;) do curl -v  -i -X PUT -u RachadAbiChahine:${TOKEN} -d {"\"path\":\"${CHART}\",\"message\":\"update\", \"content\":\"$(openssl base64 -A -in ./${CHART})\", \"branch\":\"master\",\"sha\":$(curl -u RachadAbiChahine:${TOKEN} -X GET https://api.github.com/repos/RachadAbiChahine/helm-charts-repo/contents/${CHART} | jq .sha)}" "https://api.github.com/repos/RachadAbiChahine/helm-charts-repo/contents/${CHART}"; done
